# Generated by Django 5.2.8 on 2025-12-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='prompt_template',
            field=models.TextField(blank=True, null=True, verbose_name='Diretrizes para IA'),
        ),
    ]
