# Generated by Django 5.2.8 on 2025-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_prompt_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='prompt_template',
            field=models.TextField(blank=True, default='\n        - "nome do cliente"\n        - "data de emissao"\n        - "data de vencimento"\n        - "codigo do cliente - uc"\n        - "mes de referencia"\n        - "consumo kwh"\n        - "valor a pagar"\n        - "Economia" \n        - "historico de consumo" (lista de objetos com "mês" e "consumo" em ordem cronológica se possível)\n        - "saldo acumulado"\n        - "preco unit com tributos"\n        - "Energia Atv Injetada"\n        ', null=True, verbose_name='Diretrizes para IA'),
        ),
    ]
