# Generated by Django 5.2.8 on 2025-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clientecontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_VIP',
            field=models.BooleanField(default=False),
        ),
    ]
