# Generated by Django 5.2.8 on 2025-12-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cliente_saldos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='valor_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do crédito'),
        ),
    ]
