# Generated by Django 5.2.8 on 2025-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cliente_politica_calculo_cliente_template_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='prompt_template',
            field=models.TextField(blank=True, default=' \n        "valor a pagar" =  energia_atv_injetada_valor * 0.7\n        "Economia"  =  energia_atv_injetada_valor * 0.3\n        ', null=True, verbose_name='Diretrizes para IA'),
        ),
    ]
