# Generated by Django 5.2.8 on 2025-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cliente_prompt_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='template_fatura',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
