# Generated by Django 5.2.8 on 2025-12-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cliente_politica_calculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='template_fatura',
            field=models.CharField(blank=True, default='modelo_fatura.html', max_length=100, null=True),
        ),
    ]
